name: Deploy

on:
  release:
    types: [published]

jobs:
  framework:
    runs-on: ubuntu-latest

    steps:
      - name: Release message
        id: message
        uses: actions/github-script@0.8.0
        with:
          result-encoding: string
          script: |
            return github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: ${GITHUB_REF##*/}
            }).body

      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: source

      - name: Checkout target
        uses: actions/checkout@v2
        with:
          repository: codeigniter4/framework
          token: ${{ secrets.ACCESS_TOKEN }}
          path: framework

      - name: Chmod
        run: chmod +x ./source/.github/scripts/deploy-framework

      - name: Deploy
        run: ./source/.github/scripts/deploy-framework ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/framework ${GITHUB_REF##*/}  "${{ steps.message.outputs.result }}"

  appstarter:
    runs-on: ubuntu-latest

    steps:
      - name: Release message
        id: message
        uses: actions/github-script@0.8.0
        with:
          result-encoding: string
          script: |
            console.log(github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            })

      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: source

      - name: Checkout target
        uses: actions/checkout@v2
        with:
          repository: codeigniter4/appstarter
          token: ${{ secrets.ACCESS_TOKEN }}
          path: appstarter

      - name: Chmod
        run: chmod +x ./source/.github/scripts/deploy-appstarter

      - name: Merge
        run: ./source/.github/scripts/deploy-appstarter ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/appstarter ${GITHUB_REF##*/}
